### ISSUE TITLE
Illegal callback invocation

### ISSUE THREAD

**Issue by vonovak** [prscX/react-native-bottom-action-sheet#11]
I noticed the native module uses callbacks to pass information back to JS. The problem with callbacks is that you can only call them once.

Reproduction:
build example app for ios, show alert of grid view, and tap on an item fast two times.

![rsz_simulator_screen_shot_-_iphone_6_-_2018-04-02_at_131915](https://user-images.githubusercontent.com/1566403/38194825-4a0618ca-367a-11e8-93dc-10238b174ffd.png)

**Comment by prscX** [comment]
Thanks @vonovak for raising the issue. I have made the fix for the raised issue, can you please install [V0.0.15](https://github.com/prscX/react-native-bottom-action-sheet/releases/tag/V0.0.15) and verify the same. 

Please let me know incase you still face the same issue.

- `iOS: Grid View`: In your app, grid view icons are coming correct?

Thanks
</ Pranav >
