### ISSUE TITLE
Custom content?

### ISSUE THREAD

**Issue by dragonfire1119** [prscX/react-native-bottom-action-sheet#2]
Can we have custom content in the sheet?

**Comment by prscX** [comment]
Thanks @dragonfire1119 for raising the query.

Currently it is not supported to pass a custom content since we are using native libraries. However this in my bucket list to create a bottom slider with custom content as may be a separate project.

For requirement perspective, is it possible to share broad level details of what exactly are you planning to show in the slider.

Thanks
Pranav

**Comment by ramonsenadev** [comment]
+1

**Comment by mayconmesquita** [comment]
+1

**Comment by prscX** [comment]
Closing the issue since the requested feature can't be achieved using native integrated libraries.

Thanks
</ Pranav >
