### ISSUE TITLE
Automatic pod install does not work

### ISSUE THREAD

**Issue by michalszorad** [prscX/react-native-bottom-action-sheet#20]
**OS**: macOS High Sierra 10.13.3
**node -v**: v8.11.1
**yarn -v**: 1.7.0

I need to manually `cd node_modules/react-native-bottom-action-sheet/ios/ && pod install`.

I ran `react-native link` and it has not helped.

**Comment by prscX** [comment]
Thanks @MichalSzorad for raising the issue.

Can you please share the RNBottomActionSheet version you have installed.

Thanks
</ Pranav >

**Comment by michalszorad** [comment]
@prscX My `react-native-bottom-action-sheet` version is `0.0.16`

**Comment by catherinetcai** [comment]
I'm running into the same issue on `0.0.13`

**Comment by prscX** [comment]
Hi @catherinetcai: Auto `pod` installer  was enabled from `v0.0.16` and onwards. Can you please install latest version and verify the same. Please let me know in case it does not works.

Hi @MichalSzorad: That's weird, I will look into the same. Meantime, if possible can you please share `npm logs` / `yarn logs` in order to further investigate the same.

Thanks
</ Pranav >
